-- Cleanup migration to drop all created objects safely
DROP TABLE IF EXISTS detalles_ventas CASCADE;
DROP TABLE IF EXISTS ventas CASCADE;
DROP TABLE IF EXISTS caja_turnos CASCADE;
DROP TABLE IF EXISTS clientes CASCADE;
DROP TABLE IF EXISTS productos CASCADE;
DROP TABLE IF EXISTS categorias CASCADE;
DROP TABLE IF EXISTS usuarios CASCADE;
DROP TABLE IF EXISTS tenants CASCADE;
DROP VIEW IF EXISTS productos_bajo_stock CASCADE;
DROP FUNCTION IF EXISTS fn_descontar_stock() CASCADE;
DROP FUNCTION IF EXISTS fn_set_actualizado_en() CASCADE;
DROP FUNCTION IF EXISTS public.get_tenant_id() CASCADE;
DROP FUNCTION IF EXISTS buscar_producto_pos(UUID, TEXT, INT) CASCADE;
DROP FUNCTION IF EXISTS procesar_venta(UUID, UUID, UUID, UUID, VARCHAR, NUMERIC, NUMERIC, NUMERIC, JSONB) CASCADE;
